version: '3.9'

services:
  cybershield:
    build: .
    container_name: cybershield-api
    ports:
      - "4242:4242"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
